name: twitter-to-kinesis
channels:
- defaults
- conda-forge
dependencies:
- blinker=1.4=py36_0
- flake8-import-order=0.12=py36_0
- oauthlib=2.0.2=py36_0
- pep8-naming=0.4.1=py36_0
- pyjwt=1.5.2=py36_0
- requests-oauthlib=0.8.0=py36_1
- tweepy=3.5.0=py36_0
- asn1crypto=0.22.0=py36_0
- cffi=1.10.0=py36_0
- cryptography=1.8.1=py36_0
- flake8=3.3.0=py36_0
- idna=2.6=py36_0
- mccabe=0.6.1=py36_0
- openssl=1.0.2l=0
- packaging=16.8=py36_0
- pip=9.0.1=py36_1
- py=1.4.34=py36_0
- pycodestyle=2.3.1=py36_0
- pycparser=2.18=py36_0
- pyflakes=1.5.0=py36_0
- pyparsing=2.2.0=py36_0
- pysocks=1.6.6=py36_0
- pytest=3.2.1=py36_0
- python=3.6.1=2
- pytz=2017.2=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- ruamel_yaml=0.11.14=py36_1
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zlib=1.2.11=0
- pip:
  - dateparser==0.6.0
  - python-dateutil==2.6.1
  - regex==2017.7.28
  - ruamel.yaml==0.15.31
  - tzlocal==1.4
  - urllib3==1.22
